stages: 
    - deploy
deploy:
    image: akulavishal/terraform:awscli
    stage: deploy
    script:
    - aws s3 sync . s3://$S3_BUCKET_NAME  --delete --exclude ".*" --exclude ".*/*" --exclude "*/.DAV/*"
    - aws cloudfront create-invalidation --distribution-id=$DISTRIBUTION_ID --paths "/" "/*"
    only:
    - master

